# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c82d7b2c2bab5932805b42db5f513d2c445ffd33a3dfe4d3a6a2b2c8bfd71a5aff8bfff14f3584fb7789ba5b77da3f18a593c18ec0d2552d8b2f109d783dd42

test:
  secret_key_base: bb1ab0972b951cda43f9c55832b8e54da410eb7b86f9932df20bb65764d7208c293ddae1412bbd94b248f649b8d23f7dd352a0721612df5792cc6e6eb99e1543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
